### PR TITLE
Updating initial changes

### PR DESCRIPTION
**Pull request by Femme-js**

### CODE REVIEW

**Comment by miquelduranfrigola** [comment]
Hi @Femme-js and @GemmaTuron - this is failing, probably due  to no `Input` in the metadata.

**Comment by GemmaTuron** [comment]
Hello @Femme-js 

Please do revise the Git Actions.

**Comment by DhanshreeA** [comment]
Hey @Femme-js you need to change "Chemical Language Model" to "Chemical language model"

**Comment by GemmaTuron** [comment]
Hello @Femme-js ,

The model is failing at predict time, please revise the integration of the model within Ersilia

**Comment by GemmaTuron** [comment]
We need to work on the incorporation of text inputs for this model to work.
I'll merge the PR and we will work on the main codebase when the text input is ready.

**Pull request merged**
